---
loadbalancer:
  hosts:
    lb01:
      ansible_host: lb01
webserver:
  hosts:
    app01:
      ansible_host: app01
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    db01:
      ansible_host: db01
      ansible_python_interpreter: /usr/bin/python3
deploymentmicrok8s:
  hosts:
    microk8s:
      ansible_host: 20.216.31.6
      ansible_port: 22
      ansible_ssh_user: azureuser
     
control:
  hosts:
    local-control:
      ansible_connection: local
